### ISSUE TITLE
Uploaded font files are saved in the wrong place

### ISSUE THREAD

**Issue by Alexandru-Teodorescu** [pixelgrade/fonto#16]
Am descoperit că atunci când vrei să încarci fișierele font-ului, mai jos îți generează un url cu path-ul către folderul cu font-uri. Acum dacă te duci și verifici folderul generat, se poate observa că fișierele care trebuiau să fie în el sunt salvate într-un alt fișier. [video](https://share.getcloudapp.com/Wnubmo0Z)

**Comment by vladolaru** [comment]
@Alexandru-Teodorescu This is fixed and it will be included in v1.2.0

**Comment by andreiungurianu** [comment]
This seems to happen again in v1.2.0. The folder gets created but the files are not uploaded there.
