### ISSUE TITLE
Missing font-weight property for custom fonts

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/fonto#17]
I used the [Fonto](https://github.com/pixelgrade/fonto) plugin to set up a  custom `self-hosted` font. 

For font `Weights & Style Matching` I picked that fonts are grouped together under a **single** Font Family name and I checked all the weights that are available. Here is a [screenshot](https://user-images.githubusercontent.com/1632775/118446044-d912d700-b6f7-11eb-9102-ea4659a7a9a4.png) of how the whole setup looks like.

When I moved to [Customify](https://github.com/pixelgrade/customify), I noticed that while the font is available, there is a missing font-weight selector:

![Screenshot 2021-05-17 at 09-53](https://user-images.githubusercontent.com/1632775/118446153-f8116900-b6f7-11eb-90dd-59c73056b8a6.gif)

---
This issue might be related to Customify https://github.com/pixelgrade/customify/issues/240

**Comment by vladolaru** [comment]
@georgeolaru I ended up rethinking the way Customify/Style Manager allows for such inputs like Fonto wants to do. Now all is well. 

I will include the new logic in Customify v2.11.0 and Fonto v1.2.0
