### ISSUE TITLE
Add or Upload Files button not working

### ISSUE THREAD

**Issue by raduconst** [pixelgrade/fonto#2]
Cand apas pe buton nu se intampla nimic (am incercat pluginul pe mai multe teme in speranta ca asta ar fi problema).

**Comment by vladolaru** [comment]
Am rezolvat problema in: https://github.com/pixelgrade/fonto/commit/226f1beb79d4a13173926fae558e6326f4ff5762

**Comment by vladolaru** [comment]
Am dat update la Fonto 1.0.1

**Comment by hitolonen** [comment]
Doesn't work with WP 4.8 and Fonto 1.0.2 (fresh WP install, Listable theme installed, Pixelgrade Care plugin installed, no other plugins active). 

Visual composer fix at https://github.com/pixelgrade/fonto/issues/10 could be related...
