### ISSUE TITLE
 Fix Mime Types issue for Self-Hosted Fonts

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/fonto#6]
By default in WordPress nu poti uploada fisiere precum fonturi si primesti eroarea:  “Sorry, this file type is not permitted for security reasons.”

Ca eventuale solutii, inteleg ca sunt filtre prin care putem permite anumitor extensii sa poata fi urcate: http://freewptp.com/fix-wordpress-issue-sorry-this-file-type-is-not-permitted-for-security-reasons/

Ar fi nevoie de urmatoarele extensii: `.woff, .woff2, .svg, .eot, .ttf`

**Comment by vladolaru** [comment]
@georgeolaru This is fixed/updated to the latest mime-types.
