### ISSUE TITLE
Plugin not working with Osteria

### ISSUE THREAD

**Issue by raduconst** [pixelgrade/fonto#7]
In orice fel as adauga un font, nu este afisat in field-urile pentru fonturi din Customizer. 
Ref: https://secure.helpscout.net/conversation/344997037/670/?folderId=1135400

**Comment by georgeolaru** [comment]
Cred ca tine de noul field de font (cu Select2 si grupat intr-un popover impreuna cu optiunile de Weight/Font-Size/Line-Height.

 Am testat si la `Patch` si face la fel, insa la o tema precum `Twenty Seventeen` merge ok.

**Comment by andreilupu** [comment]
Acum merge si cu noul Font-Selector
